name: fixnix_app
description: FIXNIX helpdesk app with in-app notifications
publish_to: "none"

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State & routing
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.2

  # Networking & storage
  dio: ^5.5.0+1
  flutter_secure_storage: ^9.2.2

  # Firebase push + local notifications
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.1

  # misc
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # No codegen = fewer build issues

flutter:
  uses-material-design: true
