// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc4QJP35quSRwdtZnj9QlSr5AFU_-jmbc',
    appId: '1:129673915555:web:b39067bd53f1166d1ca316',
    messagingSenderId: '129673915555',
    projectId: 'ticketapp-56785',
    authDomain: 'ticketapp-56785.firebaseapp.com',
    storageBucket: 'ticketapp-56785.firebasestorage.app',
    measurementId: 'G-B9JS28BNN5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtGG2cOSXDpKZMVpc17lyxZyd0Fsmiir4',
    appId: '1:129673915555:android:9a14c45cb410e4ce1ca316',
    messagingSenderId: '129673915555',
    projectId: 'ticketapp-56785',
    storageBucket: 'ticketapp-56785.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3EKxnsKjbF4UFuCRsUv45-xqyBQ_yctc',
    appId: '1:129673915555:ios:83359098a5bee9511ca316',
    messagingSenderId: '129673915555',
    projectId: 'ticketapp-56785',
    storageBucket: 'ticketapp-56785.firebasestorage.app',
    iosBundleId: 'com.example.fixnixFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3EKxnsKjbF4UFuCRsUv45-xqyBQ_yctc',
    appId: '1:129673915555:ios:83359098a5bee9511ca316',
    messagingSenderId: '129673915555',
    projectId: 'ticketapp-56785',
    storageBucket: 'ticketapp-56785.firebasestorage.app',
    iosBundleId: 'com.example.fixnixFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAc4QJP35quSRwdtZnj9QlSr5AFU_-jmbc',
    appId: '1:129673915555:web:3e411488488657ed1ca316',
    messagingSenderId: '129673915555',
    projectId: 'ticketapp-56785',
    authDomain: 'ticketapp-56785.firebaseapp.com',
    storageBucket: 'ticketapp-56785.firebasestorage.app',
    measurementId: 'G-928LB0HVT5',
  );
}
